src/pages/Foundations/Typography/BodyStyles/code.md, src/pages/Foundations/Typography/HeadingStyles/code.md, src/pages/Foundations/Typography/HeroStyles/code.md, src/pages/GetStarted/Developers/npmScriptTutorial/index.md
Old import using atomic structure in documentation
New import with typography and component
=> fix(documentation): wrong import for typography and components

.gitignore, packages/styles/layouts/_l.flexy.scss, src/pages/Foundations/Layout/Grid/previews/flexyCentered.preview.html
This PR fixes a typo in a class name.
The `ml-flexy--space-around` is not working because of a typo in the class name (`ml-flexy--space-aroud`).
The typo fix allows to correctly apply the space around behaviour to the flexy element.
=> fix(pattern/grids): fix typo in flexy class name

src/docs/Components/index.mdx, src/docs/Contributing/Prerequisite/GitConventions/index.mdx
We had some "comming soon" typos on the styleguide
Github issue number or Jira issue URL: [MZC-177](https://design-system-adeo.atlassian.net/browse/MZC-177?atlOrigin=eyJpIjoiNWUwMjNkZDEwODYxNDgxNzhlZGMyZmU1OGQzYzkxMTQiLCJwIjoiaiJ9)
=> fix(website): fixing some typos

packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss, src/docs/Contributing/Prerequisite/CSSConventions/index.mdx, src/docs/Contributing/Prerequisite/InstallForDev/index.mdx, src/docs/Contributing/ReportBug/index.mdx, src/docs/Contributing/SubmitChanges/AddNewPattern/index.mdx, src/docs/Contributing/SubmitChanges/DesignToolsConventions/index.mdx, src/docs/Contributing/SubmitChanges/PatternEnhancement/index.mdx, src/docs/Contributing/SubmitChanges/SubmitBugFix/index.mdx, src/docs/Contributing/SubmitChanges/SubmitNewPattern/index.mdx
Fixes edge effects that appeared after refactoring Contributing pages
Github issue number or Jira issue URL: **176**
=> fix(onboard/side effects): fix side effects after reorganize contrib pages

src/docs/Foundations/Layout/MarginAndPaddings/code.mdx
**Wrong var names for spacings**
Github issue number or Jira issue URL: https://github.com/adeo/mozaic-design-system/issues/474
=> fix(website/spacings): wrong var names - Fixes #474

README.md, src/docs/Components/Buttons/code.mdx, src/docs/Components/Flags/index.mdx, src/docs/Contributing/Designers/AddNewIcons/index.mdx, src/docs/Contributing/Designers/DesignToolsConventions/index.mdx, src/docs/Contributing/Developers/CSSConventions/index.mdx, src/docs/Contributing/Developers/InstallForDev/index.mdx, src/docs/Contributing/SubmitChanges/AddNewPattern/index.mdx, src/docs/Contributing/SubmitChanges/PatternEnhancement/index.mdx, src/docs/Contributing/SubmitChanges/SubmitBugFix/index.mdx, src/docs/Contributing/SubmitChanges/SubmitNewPattern/index.mdx, src/docs/Foundations/Colors/index.mdx, src/docs/Foundations/Typography/ScaleAndSizes/index.mdx, src/docs/GetStarted/Developers/CustomizeTokens/index.mdx, src/docs/GetStarted/Developers/configureStylelint/index.mdx, src/pages/index.js
Some links are broken in the documentation, we need to fix them.
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-347
=> fix(website/links): repair broken links in the documentation

packages/styles/settings-tools/_s.magic-unit.scss, src/docs/Foundations/MagicUnit/code.mdx, src/docs/Foundations/MagicUnit/index.mdx, src/docs/Foundations/MagicUnit/sheatsheat.mdx
The variable $mu175 (28px) is missing and at the same time correct some errors in the documentation.
Github issue number or Jira issue URL: [MZC-356](https://design-system-adeo.atlassian.net/browse/MZC-356)
=> fix(pattern/magic-unit): add $mu175 variable and spell-check

packages/styles/components/_c.notification.scss
Fix #512
Remove unnecessary css rules on the notification pattern
Github issue number or Jira issue URL: [ISSUE-512](https://github.com/adeo/mozaic-design-system/issues/512)
=> fix(patterns/notification): remove unnecessary css rules

packages/styles/components/_c.stars-input.scss
Fix background-image size on rating-stars input
=> fix(patterns/rating-stars): add background-size on rating stars input

packages/styles/components/_c.button.scss
There has been a regression on the color of the icons in the buttons.
GitHub issue number or Jira issue URL: QuickFix
=> fix(patterns/buttons): fix regression on the color of icons

packages/gatsby-theme-styleguide/src/gatsby-components/Container/Container.js, packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js, packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss, packages/gatsby-theme-styleguide/src/gatsby-components/base.scss, packages/gatsby-theme-styleguide/src/gatsby-components/layout.js, packages/gatsby-theme-styleguide/src/templates/pattern-page.js
Make the website responsive
GitHub issue number or Jira issue URL: [ID-6798](https://adeo.kanbanize.com/ctrl_board/10/cards/6798/details/)
=> refactor(website/responsive): make the website responsive

packages/styles/components/_c.checkbox.scss, packages/styles/components/_c.radio.scss, packages/styles/components/_c.toggle.scss
Remove white-space property on .mc-toggle__label
GitHub issue number or Jira issue URL: [ID-7139](https://adeo.kanbanize.com/ctrl_board/10/cards/7139/details/)
=> fix(patterns/toggle): remove white-space property on .mc-toggle__label

packages/styles/components/_c.accordion.scss, src/docs/Components/Accordion/code.mdx, src/docs/Components/Accordion/previews/icon.preview.html, src/docs/Components/Accordion/previews/no-padding.preview.html
Set display:flex only if label has an icon
GitHub issue number or Jira issue URL: #mozaic-support
=> fix(patterns/accordions): set display:flex only if label has an icon

packages/styles/components/_c.accordion.scss
Update max-height value when accordion is open
GitHub issue number or Jira issue URL: From Slack #mozaic-support
=> fix(patterns/accordions): update max-height value when accordion is open

packages/styles/components/_c.flag.scss, packages/styles/settings-tools/_s.flags.scss, src/docs/Components/Flags/code.mdx
Fix #669
Allow the use of a multi-line flag for certain cases
GitHub issue number or Jira issue URL: [ISSUE-669](https://github.com/adeo/mozaic-design-system/issues/669)
=> feat(patterns/flag): prevent flag from shrinking + add modifier for multi-line flag

packages/styles/components/_c.links.scss
Fix #684
Avoid the link icon from shrinking
GitHub issue number or Jira issue URL: [ISSUE-684](https://github.com/adeo/mozaic-design-system/issues/684)
=> fix(patterns/mc-link): avoid the link icon from shrinking

packages/styles/components/_c.breadcrumb.scss, src/docs/Components/Breadcrumb/previews/responsive.preview.html
Adjust breadcrumb behavior on smaller breakpoints, the arrow must not be centered if the content is on two or more lines.
=> fix(patterns/breadcrumb): adjust breadcrumb behavior on smaller breakpoints

packages/styles/components/_c.hero.scss
Remove unnecessary z-index on **.mc-hero__boxed** element
=> fix(patterns/hero): remove unnecessary z-index on hero boxed content

packages/styles/settings-tools/_t.reset-forms.scss
GitHub issue number or Jira issue URL: [ISSUE-740](https://github.com/adeo/mozaic-design-system/issues/740)
=> fix(pattern/qtyselector): remove spin button in mozilla

packages/styles/settings-tools/_s.inline-icons.scss
Add arrow-top-16 in sass inline-icons function
=> feat(patterns/icons): add arrow-top-16 in sass inline-icons function

packages/styles/components/_c.accordion.scss, src/docs/Components/Accordion/previews/stacked.preview.html, src/docs/Components/Accordion/previews/stacked.preview.scss
Fix #754
**a11y - manage focusable elements on closed accordion**
GitHub issue number or Jira issue URL: **Fix** #754
=> fix(patterns/accordion): a11y - manage focusable elements on closed accordion

.browserslistrc, package.json
Use the dedicated `.browserslistrc` file instead of the **browserslist** key in package.json.
=> refactor(chore/browserslist): implement .browserslistrc file

packages/styles/layouts/_l.flexy.scss
Add two new modifiers : 
`.ml-flexy--justify-between` => To implement the **justify-content: space-between;** rule
`.ml-flexy--grow` => To implement the **flex-grow: 1** rule
=> feat(layout/grid): add '--justify-between' and '--grow' modifiers

packages/styles/components/_c.card.scss
**Unify unboxed & outlined cards width on breakpoint M**
=> fix(patterns/card): unify unboxed & outlined cards width on breakpoint M

packages/styles/components/_c.tabs.scss
On the dropdown navigation implementation of the tabs component, the `::before` pseudo-element element the use of the select.
Can see this behaviour on this link : https://adeo.github.io/mozaic-vue/?path=/story/components-mtab--showcase
=> fix(pattern/tabs): add a pointer-events on tabs dropdown variation

packages/styles/components/_c.layer.scss, packages/styles/components/_c.modal.scss, packages/styles/settings-tools/_all-settings.scss, packages/styles/settings-tools/_s.modal.scss
Create and use Sass mixins to standardize the common code between the layer and modal components
=> refactor(patterns/modal): standardize common code between layer and modal

packages/styles/components/_c.layer.scss, packages/styles/components/_c.modal.scss
Set 'pointer-events:all' only when dialog is opened
=> refactor(patterns/modal): set pointer-events only when open

src/docs/Components/Form/PhoneNumberInput/code.mdx, src/docs/Components/Form/PhoneNumberInput/previews/label.preview.html
**Remove the use of .mc-field__input on input tag**
=> refactor(patterns/phonenumberinput): remove the use of .mc-field__input on input tag

packages/styles/components/_c.tooltip.scss
Prevent side-effects when using white-space on parent elements
=> fix(patterns/tooltip): prevent side-effects when using white-space on parent elements

packages/styles/components/_c.breadcrumb.scss
=> refactor(patterns/breadcrumb): fix CSS class mc-link typo

packages/styles/components/_c.layer.scss
Make the layer's shadow unclickable
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-vue/issues/348
=> fix(patterns/layer): make the layer's shadow unclickable

packages/tokens/build/js/tokensObject.js, packages/tokens/properties/color/tabs.json
Use primary colors tokens for the tab component
=> fix(tokens/tabs): use primary colors tokens for the tab component

packages/styles/components/_c.button.scss
Ensure that the buttons with icons keep the right height
=> fix(component/button): ensure that the buttons with icons keep the right height

packages/styles/components/_c.accordion.scss, src/docs/Components/Accordion/previews/stacked.preview.html
Allow title to go to line on small screens
=> fix(component/accordion): allow title to go to line on small screens

packages/styles/settings-tools/_s.fonts-faces.scss
Set the Roboto font-family when using the Adeo preset
GitHub issue number or Jira issue URL: [MZC-147](https://jira.adeo.com/browse/MZC-147)
=> feat(pattern/font): set the Roboto font-family when using the Adeo preset

packages/css-dev-tools/postcssPluginConfig.js, packages/gatsby-theme-styleguide/src/gatsby-components/SiteMapData/SiteMapData.js
When the `yarn develop` command is run after some time, the following code appears: 
```shell
warn This query took more than 15s to run — which is unusually long and might indicate you're querying too much or have some unoptimized code:
File path: /home/tii/clients/adeo/mozaic/mozaic-design-system/packages/gatsby-theme-styleguide/src/gatsby-components/SiteMapData/SiteMapData.js
Therefore, in order to reduce the execution time of this request, I removed the keys that are not used in the code of the styleguide theme
```
=> refactor(website/sitemapdata): remove unused keys in the SiteMapData query

package.json
When using the `yarn develop` command, Gatsby becomes increasingly slow.
This PR aims to remove the systematic deletion of the cache at the start of the develop phase. This is to see if we can take advantage of the cache generated by Gatsby to improve performance.
=> build(npm-scripts/predevelop): remove the clean-cache command when running predevelop

packages/styles/components/_c.accordion.scss
Change the way the trigger input is hidden.
Hide the trigger input with the `visually-hidden()` mixin and no longer with an absolute position
=> refactor(component/accordion): change the way the trigger input is hidden

packages/styles/components/_c.layer.scss, packages/styles/components/_c.loader.scss, packages/styles/components/_c.modal.scss, packages/styles/components/_c.overlay.scss, packages/styles/settings-tools/_all-settings.scss, packages/styles/settings-tools/_s.loader.scss, packages/styles/settings-tools/_s.modal.scss, packages/styles/settings-tools/_s.overlay.scss, src/docs/Components/Loader/code.mdx, src/docs/Components/Loader/index.mdx, src/docs/Components/Loader/overlay.mdx, src/docs/Components/Loader/previews/default.preview.html, src/docs/Components/Loader/previews/default.preview.scss, src/docs/Components/Loader/previews/opening.preview.html, src/docs/Components/Loader/previews/opening.preview.scss, src/docs/Components/Loader/previews/overlay-text.preview.html, src/docs/Components/Loader/previews/overlay-text.preview.scss, src/docs/Components/Loader/previews/overlay.preview.html, src/docs/Components/Loader/previews/overlay.preview.scss, src/docs/Components/Loader/previews/sizes.preview.html, src/docs/Components/Loader/previews/sizes.preview.scss, src/docs/Components/Loader/previews/themes.preview.html, src/docs/Components/Loader/previews/themes.preview.scss
Add the new Loader component
GitHub issue number or Jira issue URL:
- JIRA: https://jira.adeo.com/browse/PDPUI-26
- Figma: https://www.figma.com/file/DE6kAicnCe1Ax0agca1P1Y/%F0%9F%9A%A7-Loaders-(beta)?node-id=604%3A15312
- Github issue: #1052
=> feat(component/loader): add the new Loader component

packages/styles/components/_c.toggle.scss
**Maintain the input position within the component**
Details of the problem:
The input tag of the Toggle component is hidden using accessible hiding which has a `position: absolute` rule.
This behaviour causes a problem on Chrome when the layer contains this component.
=> fix(component/toggle): maintain the input position within the component

packages/styles/components/_c.breadcrumb.scss, src/docs/Components/Breadcrumb/previews/dark-mode.preview.scss
Remove `padding-left` & dark `background-color`
GitHub issue number or Jira issue URL: https://jira.adeo.com/browse/MZC-165
=> feat(component/breadcrumb): remove `padding-left` & dark `background-color`

packages/styles/components/_c.phone-number.scss
In the **PhoneNumberInput** implementations on **Vue.js** & **Webcomponents**, CSS code is hardcoded in the styles part of the concerned files.
So I took this code to insert it in the `@mozaic-ds/styles package`, in order to have a "cleaner" management of this component.
=> feat(component/phonenumber): add additional styles

packages/styles/components/_c.option-card.scss, packages/styles/settings-tools/_t.selectors.scss
=> fix(component/option-card): manage the use of the @at-root selector differently

packages/styles/layouts/_l.flexy.scss
Improve `.ml-flexy__col` selector scopable behaviour
=> fix(layouts/grid): improve `.ml-flexy__col` selector scopable behaviour

packages/styles/components/_c.layer.scss, src/docs/Components/Layers/code.mdx, src/docs/Components/Layers/previews/border-scroll-bar.preview.html, src/docs/Components/Layers/previews/border-scroll-bar.preview.scss, src/docs/Components/Layers/previews/cta-link.preview.html, src/docs/Components/Layers/previews/cta-link.preview.scss, src/docs/Components/Layers/previews/cta-two.preview.html, src/docs/Components/Layers/previews/cta-two.preview.scss, src/docs/Components/Layers/previews/default.preview.html, src/docs/Components/Layers/previews/extended.preview.html, src/docs/Components/Layers/previews/header-with-icon.preview.html, src/docs/Components/Layers/previews/open-ltr.preview.html, src/docs/Components/Layers/previews/scrolling-content.preview.html, src/docs/Components/Layers/previews/scrolling-content.preview.scss, src/docs/Components/Layers/previews/without-footer.preview.html, src/docs/Components/Modals/code.mdx, src/docs/Components/Modals/previews/opening.preview.html, src/docs/Components/Modals/previews/opening.preview.scss
Resolves #1059
Delete the `.mc-layer-overlay` & `.mc-modal-overlay` classes in favor of `.mc-overlay`
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-design-system/issues/1059
=> feat(component/overlay): delete the `.mc-layer-overlay` & `.mc-modal-overlay` classes in favor of `.mc-overlay`

packages/styles/components/_c.phone-number.scss
Remove `z-index` on `.mc-phone-number__dropdown` element
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-web-components/issues/439
=> fix(component/phninput): remove `z-index` on `.mc-phone-number__dropdown` element

packages/styles/components/_c.layer.scss, packages/styles/components/_c.modal.scss
**Improve overlay for scoped modules**
When the Layer or Modal stylesheet is called in a scoped module, the overlay must not be wrapped in the module selector.
=> fix(components/modal/layer): improve overlay for scoped modules

packages/styles/settings-tools/_s.overlay.scss
Remove `cursor:pointer` on overlay
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-vue/issues/861
=> fix(component/overlay): remove `cursor:pointer` on overlay

packages/styles/components/_c.breadcrumb.scss
Add the modifier `no-padding`.
The removal of padding from the Breadcrumb component [has been done as part of the next major version](https://github.com/adeo/mozaic-design-system/pull/1098) of Mozaic.
However, some teams at LMFR have the need to use a Breadcrumb without padding in advance.
This is the reason for adding this new modifier.
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-design-system/issues/1224
=> fix(components/tabs): add the modifier `no-padding`

packages/styles/components/_c.autocomplete.scss, packages/styles/components/_c.dropdown.scss, src/docs/Components/Form/Autocomplete/code.mdx, src/docs/Components/Form/Autocomplete/previews/default.preview.html, src/docs/Components/Form/Autocomplete/previews/disabled.preview.html, src/docs/Components/Form/Autocomplete/previews/invalid.preview.html, src/docs/Components/Form/Autocomplete/previews/multi.preview.html, src/docs/Components/Form/Dropdown/code.mdx, src/docs/Components/Form/Dropdown/previews/default.preview.html, src/docs/Components/Form/Dropdown/previews/disabled.preview.html, src/docs/Components/Form/Dropdown/previews/invalid.preview.html, src/docs/Components/Form/Dropdown/previews/multi.preview.html
Adjust the padding-right value according to the clear button
=> fix(components/autocomplete-dropdown): adjust the padding-right value according to the clear button

packages/styles/components/_c.option-card.scss, src/docs/Components/OptionGroup/OptionCard/code.mdx, src/docs/Components/OptionGroup/OptionCard/previews/withcontent.preview.html, src/docs/Components/OptionGroup/OptionCard/previews/withcontent.preview.scss
Make the content element height's suitable to the parent
=> fix(component/option-card): make the content element height's suitable to the parent

packages/styles/components/_c.autocomplete.scss, packages/styles/components/_c.dropdown.scss, src/docs/Components/Form/Autocomplete/code.mdx, src/docs/Components/Form/Autocomplete/previews/default.preview.html, src/docs/Components/Form/Autocomplete/previews/invalid.preview.html, src/docs/Components/Form/Autocomplete/previews/multi.preview.html, src/docs/Components/Form/Dropdown/code.mdx, src/docs/Components/Form/Dropdown/previews/default.preview.html, src/docs/Components/Form/Dropdown/previews/invalid.preview.html, src/docs/Components/Form/Dropdown/previews/invalid.preview.scss, src/docs/Components/Form/Dropdown/previews/multi.preview.html, src/docs/Components/Form/Dropdown/previews/multi.preview.scss
Add the `clearable` modifier to manage the display of the clear button
=> feat(component/autocomplete-dropdown): add the `clearable` modifier to manage the display of the clear button

packages/styles/components/_c.datatable.scss
Improve the overflow behaviour of the datatable
GitHub issue number or Jira issue URL: https://adeo-tech-community.slack.com/archives/CKQJZL7C4/p1672037763187509
=> fix(component/datatable): improve the overflow behaviour of the datatable

packages/styles/components/_c.modal.scss
Set a `min-height` value for the modal's header
=> refactor(component/modal): set a `min-height` value for the modal's header

packages/gatsby-source-preview/gatsby-node.js
=> chore(previews): avoid reloading all previews when scss changes

packages/styles/settings-tools/_s.fonts-scale.scss
**Make the `font-size` definition relative to the magic-unit value**
Currently, when a user customizes the value of the variable `$local-rem-value`, the values of the paddings & margins, update well, because they are based on the **magic-unit**. 
However the font-size of the components defined with the mixin `set-font-scale()` it does not adapt.
So we should link the property value `font-size` to the value of the **magic-unit**, so that the font-size also adapts when the value of the variable `$local-rem-value` changes.
=> feat(styles/settings): make the `font-size` definition relative to the magic-unit value

packages/styles/components/_c.stepper.scss
Remove default background of 'indicator' element
=> fix(component/stepper): remove default background of 'indicator' element

packages/styles/components/_c.stars-input.scss
I have this following error when `c.stars-input` is imported: `[sass] expected ";".` on `background-image` CSS tag.
I reproduced the error on this minimalist repo: https://github.com/pinguet62/mozaic-starsinput
ℹ️ You can find distinct commits.
Apparently there is an [issue between `url()` and SASS variables](https://stackoverflow.com/questions/8608498/have-a-variable-in-images-path-in-sass) and a workaround is to use interpolation.
And wrap some SASS variable with `#{ }` seems fix the problem.
I don't know if it's the best solution 😉
=> fix(component/stars-input): stringify "background-image" parameter to avoid ";" expectation SASS error

packages/styles/components/_c.modal.scss, src/docs/Components/Modals/code.mdx, src/docs/Components/Modals/previews/big-content.preview.html, src/docs/Components/Modals/previews/big-content.preview.scss
This PR changes the Modal component code so that long content is managed by default without the need to add a modifier.
The code therefore makes the following changes:
- Delete the `mc-modal--overflow` modifier
- Removal of the shadow on the footer (to be ISO with Figma mock-ups)
- Inclusion of certain style evolutions made on the [Mozaic-React](https://github.com/adeo/mozaic-react/blob/master/src/components/Modal/Modal.scss) side
=> fix(component/modal): manage long content by default

packages/styles/components/_c.accordion.scss
In Mozaic Vue, the accordion isn't opening when clicking on text due to the label tag.
I had a pointer-events: none on the label to fix this.
=> fix: label prevents clicking on the accordion

packages/styles/components/_c.accordion.scss
This reverts commit ffd367f0e00d4699420efa85cfd9249a78eb6d0b.
> We go back to the previous version because this evolution creates side effects in the libs that consume this evolution.
=> Revert "fix: label prevents clicking on the accordion (#1448)"

packages/styles/components/_c.option-card.scss
Add `position:relative` on focusable elements
GitHub issue number or Jira issue URL: 
related to => https://github.com/adeo/mozaic-vue/issues/1489
=> fix(component/optioncard): add `position:relative` on focusable elements

src/docs/Components/DataTable/index.mdx
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-web-components/issues/764
Figma prototype: https://www.figma.com/proto/Fwvg2vuovdgIZZudFzwmLG/02.-Datatable-%F0%9F%94%B5?page-id=578%3A79523&type=design&node-id=3849-51504&viewport=193%2C-128%2C0.26&t=CbFkLJpaf5KhOoRb-1&scaling=min-zoom&starting-point-node-id=3849%3A51504&mode=design
=> docs(datatable): fix mass selection behaviour

packages/styles/settings-tools/_s.inline-icons.scss
Re-add the `notification-circle-available-24` icon deleted by mistake
=> fix(settings/icons): re-add the 'notification-circle-available-24' icon

packages/styles/components/_c.datatable-header.scss
Remove unnecessary paddings from datatable header elements
PR brought back from https://github.com/adeo/ads-styles/pull/20
=> fix(component/datatable): remove unnecessary paddings from datatable header elements

packages/styles/components/_c.accordion.scss, packages/styles/settings-tools/_s.accordions.scss
This PR includes the following changes: 
- Removal of the code for the old accordion structure
- Improved behaviour when elements are inserted before the label (checkbox / toggle)
- Improved no-padding behaviour
PR brought back from https://github.com/adeo/ads-styles/pull/18
=> feat(component/accordion): clean & improve component styles

.github/workflows/push.yml, .github/workflows/release.yml
Replace custom `SVC_GH_API_TOKEN` with standard `GITHUB_TOKEN`
=> ci(gha/workflows): replace custom `SVC_GH_API_TOKEN` with standard `GITHUB_TOKEN`

packages/styles/components/_c.tooltip.scss
To make the Tooltip component usable by keyboard, we need to display the tooltip when the component receives focus from keyboard navigation. Today, there is no possibility for keyboard-only users to focus and see the component.
Github issue number : #1545 
The PR is linked with [this other PR](https://github.com/adeo/mozaic-react/pull/220), for mozaic react. The mozaic react PR doesn't work without this one.
=> fix(Tooltip): make tooltip usable by keyboard for accessibility

packages/styles/components/_c.breadcrumb.scss
Remove extra padding on 1st only-child item on desktop viewport.
Related https://github.com/adeo/mozaic-vue/issues/1821
=> fix(component/breadcrumb): remove extra padding on 1st item

packages/styles/components/_c.listbox.scss
Re-add styles relating to ListboxActions position
Related to https://github.com/adeo/mozaic-vue/issues/1836
=> fix(component/listbox): re-add styles relating to ListboxActions position

packages/styles/components/_c.tooltip.scss
Word breaks in tooltips where cutting words for no reason.
`word-break: break-word` is deprecated so maybe we should use
`overflow-wrap: break-word` instead
I don't know if it was on purpose to force cutting words in tooltips but it cause some UX/UI issues in our team
Example:
=> fix(component/tooltip): update word-break to avoid cutting word in half

packages/styles/components/_c.textarea.scss
Limit resize beyond the max width
Fix #1469
=> fix(component/textarea): limit resize beyond the max width

packages/styles/components/_c.datatable-empty.scss, packages/styles/components/_c.datatable.scss
read [What is a breaking change ?](https://mozaic.adeo.cloud/contributing/developers/git-conventions/#breaking-changes-)
Update the display of empty states to be fully consistent with Figma mockups
**Figma mockups:**
https://www.figma.com/file/Fwvg2vuovdgIZZudFzwmLG/02.-Datatable-%F0%9F%94%B5?type=design&node-id=4889-92340&mode=design&t=YwzoTVTHAFHpQGhS-4
=> feat(components/datatable): update empty states display

packages/styles/components/_c.datatable.scss
Restrict the application of some styles to the root table
=> feat(components/datatable): restrict the application of some styles to the root table

packages/styles/components/_c.stepper.scss
Compact variation - not take `skrinked` variation into account.
=> fix(components/stepper): compact variation - not take `skrinked` variation into account

packages/styles/components/_c.listbox.scss
On the listbox, there was no visual clue when an element of the list has the focus. The change applies the same style on focus as on the hover.
[1588](https://github.com/adeo/mozaic-design-system/issues/1588)
=> fix(listbox): set same style on hover and focus

packages/tokens/config.js
We use Mozaic on the [Front-End Enablers portal](https://fee.adeo.cloud/) and we customized tokens to have our own primary colors.
Here is our mozaic.config.js :
```javascript
module.exports = {
preset: 'adeo',
tokens: {
localTokensSrcPath: './src/styles/tokens/',
localTokensExportPath: './dist/tokens/',
},
...
};
```
It used to work for a while, but recently when we upgraded `@mozaic-ds/tokens` from `1.68.0` to `1.72.0`, and our custom tokens where not taken into consideration anymore.
After some investigations, it seems that now the `localTokensSrcPath` is relative to `node_modules/@mozaic-ds/tokens/` and not the root of the project as it used to be.
I updated our Mozaic configuration with the following and it works well:
```javascript
module.exports = {
preset: 'adeo',
tokens: { …
```
=> fix(tools/tokens): custom source path should be relative to project root

packages/styles/components/_c.listbox.scss
At present, the minimum width of the component is set at 288px in accordance with the Figma mock-ups.
However, some teams have expressed the wish to have a smaller width in certain cases.
This PR allows users to adjust the `min-width` value using a CSS variable.
=> feat(component/listbox): allow the `min-width` to be changed

packages/styles/components/_c.listbox.scss
In the previous PR, the case of the "Actions" version of the Listbox was not dealt with.
In fact, in the context of the Listbox (Actions) the focus is not on inputs _(because there are none)_ but rather on focusable elements of the `<label>` ou `<a href="#">` type which have the class `mc-listbox__label`.
This PR corrects this shortcoming and standardises the focus behaviour between the "Options" and "Actions" variations of the component.
=> fix(component/listbox): standardise focus status

packages/styles/components/_c.textarea.scss
Adjust text color to disabled state
=> fix(component/textarea): adjust text color to disabled state

packages/styles/settings-tools/_s.buttons.scss, src/docs/Components/Buttons/accessibility.mdx, src/docs/Contributing/Developers/InstallForDev/index.mdx
The description is documented in the committed file `accessibility.mdx`.
In a few words, this encourages the usage of `aria-disabled="true"` on buttons, for them to stay focusable for people with disabilities. 
The CSS of buttons have been updated accordingly.
The pertinence of the pattern has been discussed with @BertrandLaot.
IMPORTANT: As I have not been able to run the design system locally, it is highly recommended to try the changes on a working machine.
=> feat(buttons): promotes aria-disabled for buttons for A11Y sake
