packages/css-dev-tools/package.json, packages/css-dev-tools/postcssPluginConfig.js, packages/styles/components/_c.text-input.scss, packages/styles/settings-tools/_all-settings.scss, packages/styles/settings-tools/_s.inline-icons.scss, src/pages/Components/TextInput/index.md, yarn.lock
=> feat(patterns/inputs): add base64 postcss + state icon inputs

packages/styles/components/_c.text-input.scss
Issue Number: https://design-system-adeo.atlassian.net/browse/MZC-90
=> fix(pattern/inputs): fix size and alignment of inputs

.github/main.workflow, ci/deploy.js, ci/docker-wait/Dockerfile, ci/docker-wait/entrypoint.sh, package.json
=> fix(ci): wait if an other deploy is pending

packages/styles/components/_c.textarea.scss, src/pages/Components/TextArea/code.md, src/pages/Components/TextArea/previews/TextArea.preview.html, src/pages/Components/TextArea/previews/TextArea.preview.scss, src/pages/Components/TextArea/specs.md
Issue Number: https://design-system-adeo.atlassian.net/browse/MZC-52
=> feat(pattern/textarea): add textarea dev docs and styles

src/data/icons.json, src/pages/index.js, src/pages/index.scss
=> fix(logo/hp): add logo on HP and adapt heading part

src/pages/index.js
- [ n/a ] The commit message follows our guidelines: https://github.com/adeo/design-system--styleguide/blob/master/CONTRIBUTING.md#commit
- [ n/a ] Tests for the changes have been added (for bug fixes / features)
- [ n/a ] Docs have been added / updated (for bug fixes / features)
=> fix(styleguide/home): typo with ressources word

src/pages/Contributing/Conventions/index.md, src/pages/Contributing/GitConventions/index.md, src/pages/Contributing/Glossary/index.md, src/pages/Contributing/Help/index.md, src/pages/Contributing/Philosophy/index.md, src/pages/Contributing/ReportBug/index.md, src/pages/Contributing/SubmitBugFix/index.md, src/pages/Contributing/SubmitNewPattern/index.md, src/pages/Contributing/SubmitPatternEnhancement/index.md, src/pages/Contributing/SuggestNewPattern/index.md, src/pages/Contributing/SuggestPatternEnhancement/index.md, src/pages/Contributing/TechnicalDocumentation/index.md, src/pages/Contributing/index.md
We don"t have any contributing documentation
Issue Number: MZC-102
Suggest a file structure for contributing documentation
=> feat(documentation): contributing documentation files structure

packages/gatsby-github-release/gatsby-node.js
Issue Number: https://design-system-adeo.atlassian.net/browse/MZC-121
fix the version selector by removing a dash
=> fix(styleguide/version select): return the right styleguide version

.github/main.workflow, .gitignore, ci/deploy.js, packages/gatsby-github-release/gatsby-node.js, packages/gatsby-github-release/package.json, src/data/icons.json, yarn.lock
=> Fix version patch

.github/main.workflow, ci/deploy.js, packages/gatsby-github-release/gatsby-node.js
=> test(build): launch pipeline

src/pages/Components/index.md, src/pages/Contributing/GitConventions/index.md, src/pages/Contributing/InstallAndRun/index.md, src/pages/Contributing/SubmitBugFix/index.md, src/pages/Contributing/SubmitNewPattern/index.md, src/pages/Contributing/SubmitPatternEnhancement/index.md, src/pages/Contributing/SuggestNewPattern/index.md, src/pages/Contributing/SuggestPatternEnhancement/index.md, src/pages/Contributing/TechnicalDocumentation/index.md, src/pages/Contributing/index.md
Issue Number: MZC-126
Complete the contributing documentation adding the git conventions
=> feat(pages/contributing): add git convention to contributing

src/pages/Contributing/Glossary/index.md
=> feat(onboard/glossary): add glossary

src/pages/Contributing/Help/index.md
=> feat(onboard/help): add need help page

src/pages/Contributing/DesignTokens/index.md
Create docs about design tokens
=> feat(onboard/design tokens): create docs about design tokens

src/pages/Contributing/CSSConventions/Concept/index.md, src/pages/Contributing/CSSConventions/DeclarationOrders/index.md, src/pages/Contributing/CSSConventions/Formatting/index.md, src/pages/Contributing/CSSConventions/Naming/index.md, src/pages/Contributing/CSSConventions/index.md
=> feat(onboard/css conventions): create docs about css conventions

src/pages/Contributing/Install/index.md
…for contributors
Use paths to new repo name (mosaic-design-system) and to docs URL
=> fix(onboard/contributing install): change paths to new repo name

.github/PULL_REQUEST_TEMPLATE.md, src/docs/Contributing/GitConventions/index.mdx
=> fix(chore/pr template): update git conventions and PR template

package.json, yarn.lock
Github issue number or Jira issue URL: 
https://design-system-adeo.atlassian.net/browse/MZC-95
use lerna exec to trigger NPM publish and add util that check if a packages is updatable before trying.
=> fix(chore/npm publish): fix npm publish command (hopefuly)

src/docs/Contributing/ReportBug/index.mdx
This PR introduce the documentation for the "Report a bug" page.
Issue Number: MZC-125
=> feat(onboard/contributing): documentation - report a bug

src/docs/Components/Flags/code.mdx, src/docs/Components/Flags/previews/flag-all.preview.scss, src/docs/Components/Flags/previews/flag-basic.preview.scss, src/docs/Components/Flags/previews/flag-bordered.preview.scss, src/docs/Components/Flags/previews/flag-default.preview.scss, src/docs/Components/Flags/previews/flag-solid.preview.scss
The flags were broken because the font was missing.
Github issue number or Jira issue URL: **MZC-158**
=> fix(patterns/flags): fix flags issues

package.json
=> fix(chore/releases): fix npm publish (hopefully again)

.github/ISSUE_TEMPLATE/1-styleguide-bug-report.md, .github/ISSUE_TEMPLATE/2-styleguide-feature-request.md, .github/ISSUE_TEMPLATE/3-pattern-addition-proposal.md, .github/ISSUE_TEMPLATE/4-pattern-bug-report.md, .github/ISSUE_TEMPLATE/5-pattern-enhancement-proposal.md, .github/ISSUE_TEMPLATE/6-other.md
Update templates Github for Issues
Github issue number or Jira issue URL: **MZC-147**
=> fix(tools/github templates): update github templates for issues

packages/gatsby-theme-styleguide/gatsby-config.js, packages/gatsby-theme-styleguide/package.json, packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js, packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/TableOfContents.js, packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/index.js, packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss, packages/gatsby-theme-styleguide/src/gatsby-components/base.scss, packages/gatsby-theme-styleguide/src/gatsby-components/layout.js, packages/gatsby-theme-styleguide/src/templates/pattern-page.js, yarn.lock
=> feat(website/toc): add table of contents

plopfile.js, src/docs/Contributing/NewPattern/AcceptanceCriterias/index.mdx, src/docs/Contributing/NewPattern/SubmitNewPattern/index.mdx, src/docs/Contributing/NewPattern/index.mdx, src/docs/Contributing/SubmitNewPattern/index.mdx, src/docs/Contributing/SuggestNewPattern/index.mdx
Add a documentation to suggest and submit a new pattern
Github issue number or Jira issue URL: **MZC-149**
=> feat(onboard/newpattern): suggest and submit a new pattern

src/docs/Contributing/PatternEnhancement/index.mdx, src/docs/Contributing/SubmitPatternEnhancement/index.mdx, src/docs/Contributing/SuggestPatternEnhancement/index.mdx
Documentation to suggest and submit a pattern enhancement
Github issue number or Jira issue URL: **MZC-167**
=> feat(onboard/patternenhancement): suggest/submit a pattern enhancement

src/docs/Contributing/ReportBug/index.mdx, src/docs/Contributing/SubmitBugFix/index.mdx
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-154
Create submit bug fixes contributing guidelines and modify the report bug one
=> feat(onboard/contrib): create contrib doc for bug fixes

packages/gatsby-theme-styleguide/src/gatsby-components/Container/Container.js, packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js, packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/TableOfContents.js, packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss, packages/gatsby-theme-styleguide/src/gatsby-components/base.scss, packages/gatsby-theme-styleguide/src/gatsby-components/layout.js, packages/gatsby-theme-styleguide/src/templates/pattern-page.js
fix broken layout after TOC and add some styles to it
=> fix(website/toc): fix layout and add some styles to the toc

src/docs/Contributing/CSSConventions/Comments/index.mdx
Add Comments section in CSS guideline documentation
Github issue number or Jira issue URL: **MZC-157**
=> feat(onboard/css comments): add comments section

.github/workflows/release.yml
Remove an unused job from GitHub action
=> fix(chore/deploy): remove unused job

packages/gatsby-theme-styleguide/src/gatsby-components/layout.js, packages/gatsby-theme-styleguide/src/templates/pattern-page.js
Fix layout to make it more responsive and to fix content size
=> fix(website/layout): render better responsive layout

src/docs/Contributing/Philosophy/index.mdx
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-170
Create the philosophy page into the contributing
=> feat(onboard/contrib): create philosophy page

src/docs/GetStarted/Developers/configurePostCss/index.mdx
Add PostCSS config for Vue.js on "Getting started"
Github issue number or Jira issue URL: **MZC-168**
=> feat(onboard/postcss vuejs): postcss config for vue.js

packages/gatsby-theme-styleguide/src/gatsby-components/Helmet/Helmet.js, packages/gatsby-theme-styleguide/src/gatsby-components/Helmet/index.js, packages/gatsby-theme-styleguide/src/gatsby-components/layout.js, src/pages/index.js
=> feat(website/feedback-module): add feedback module

src/docs/Contributing/Prerequisite/NamingConvention/index.mdx, src/docs/Contributing/SubmitChanges/DesignToolsConventions/index.mdx
Github issue number or Jira issue URL: MZC-181 (https://design-system-adeo.atlassian.net/browse/MZC-181?atlOrigin=eyJpIjoiOTM4ODMxNjc2MmQ2NDBiOGEyYmY2NmMxMGI0ZmI3MjciLCJwIjoiaiJ9)
=> feat(onboard/figma): add Figma design conventions

package.json, packages/css-dev-tools/package.json, packages/css-dev-tools/postcssPluginConfig.js, src/docs/GetStarted/Developers/configurePostCss/index.mdx, yarn.lock
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-204
- delete MQpacker
- remove docs about it
- update postcss docs
=> refactor(tools/mqpacker): remove css-mqpacker and update postcss docs

packages/icons/package.json, packages/styles/typography/_t.heros.scss, packages/web-fonts/package.json, src/docs/Components/Flags/index.mdx, src/docs/Contributing/Introduction/Philosophy/index.mdx, src/docs/Contributing/Prerequisite/CSSConventions/index.mdx, src/docs/Contributing/Prerequisite/DesignRequirements/index.mdx, src/docs/Contributing/Prerequisite/GitConventions/index.mdx, src/docs/Contributing/index.mdx, src/docs/Foundations/Layout/Grid/previews/flexyResponsive.preview.html, src/docs/Foundations/Layout/MarginAndPaddings/code.mdx, src/docs/Foundations/Shadows/index.mdx, src/docs/Foundations/Typography/FontFamilies/previews/font-families.preview.scss, src/docs/Foundations/Typography/HeadingStyles/index.mdx, src/docs/Foundations/Typography/HeroStyles/code.mdx, src/docs/Foundations/Typography/HeroStyles/design.mdx, src/docs/Foundations/Typography/HeroStyles/index.mdx, src/docs/GetStarted/Designers/aboutTheSystem/index.mdx, src/docs/GetStarted/Designers/index.mdx, src/docs/GetStarted/Designers/installation/index.mdx, src/docs/GetStarted/Designers/whatsIncluded/index.mdx, src/docs/GetStarted/Developers/CssNamingConventions/index.mdx, src/docs/GetStarted/Developers/Installation/index.mdx, src/docs/GetStarted/Developers/configurePostCss/index.mdx, src/docs/GetStarted/Developers/configureStylelint/index.mdx, src/docs/GetStarted/Developers/importingMozaicComponents/index.mdx, src/docs/GetStarted/Developers/index.mdx, src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx, src/docs/GetStarted/Developers/whatsincluded/index.mdx, src/docs/GetStarted/index.mdx
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-184
=> fix(patterns/docs): fix list of documentation typos or inacurate values

packages/styles/settings-tools/_s.spaces.scss, src/docs/Foundations/Layout/MarginAndPaddings/code.mdx
Create a padding and a margin utility class that manage at once all sides with the same value
=> feat(patterns/spaces): add an utility class to manage all sides in one css classes

src/pages/index.js
Update content of the home page. Add like for Contributing and Patterns Status page.
Github issue number or Jira issue URL: **MZC-216**
=> feat(website/home): update home page

packages/styles/components/_c.checkbox.scss, packages/styles/components/_c.radio.scss, packages/styles/components/_c.stars-input.scss, packages/styles/components/_c.stars-result.scss, packages/styles/components/_c.text-input.scss, packages/styles/settings-tools/_s.stars.scss
Fix bug for components : radio button, checkbox, input, and rating stars
Github issue number or Jira issue URL: **MZC-229**
=> fix(pattern/various): fix ie11 bugs for input, checkbox, radio and stars

packages/css-dev-tools/package.json
=> fix(tools/css-dev-tools): add missing dependency

wdio.conf.js
Github issue number or Jira issue URL:
https://design-system-adeo.atlassian.net/browse/MZC-231
=> fix(chore/test): fix screenshots for mobile devices (#231)

packages/gatsby-theme-styleguide/src/gatsby-components/layout.js, src/docs/GetStarted/Designers/installation/index.mdx, src/docs/GetStarted/Designers/whatsIncluded/index.mdx
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-237
fix ui kit link
=> fix(onboard/design kit): use dynamic link to fix kit path

packages/css-dev-tools/postcssPluginConfig.js, packages/postcss-prepend/CHANGELOG.md, packages/postcss-prepend/index.js, packages/postcss-prepend/index.test.js, packages/postcss-prepend/package.json, packages/styles/components/_c.button.scss, packages/styles/components/_c.checkbox.scss, packages/styles/components/_c.file-uploader.scss, packages/styles/components/_c.radio.scss, packages/styles/components/_c.select.scss, packages/styles/components/_c.text-input.scss, packages/styles/components/_c.textarea.scss, packages/styles/dev-utils/_qdu.magic-unit-grid.scss, packages/styles/settings-tools/_all-settings.scss, packages/styles/settings-tools/_s.buttons.scss, packages/styles/settings-tools/_s.links.scss, packages/styles/settings-tools/_t.demo-state-class.scss, src/docs/Foundations/MagicUnit/code.mdx, src/docs/Foundations/MagicUnit/previews/mdu-magic-unit-grid.preview.html, src/docs/Foundations/MagicUnit/previews/mdu-magic-unit-grid.preview.scss
As a mozaic developper I want to have styles that are generated only in dev mode
Github issue number or Jira issue URL: **MZC-219**
=> feat(tools/devmode): manage dev or production mode for scss

packages/css-dev-tools/package.json
Add @mozaic-ds/postcss-prepend and dotenv to css-dev-tools package.json
=> fix(tools/css-dev-tools): add dotenv and @mozaic-ds/postcss-prepend

packages/gatsby-github-release/gatsby-node.js, packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuVersionSelect.js, packages/gatsby-theme-styleguide/src/gatsby-components/Menu/__tests__/MenuVersionSelect.test.js, packages/gatsby-theme-styleguide/src/gatsby-components/Menu/__tests__/__snapshots__/MenuVersionSelect.test.js.snap, yarn.lock
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-263
- fix deploy urls
- add latest option (to get back to mozaic.adeo.cloud when viewing an older version)
- add tests
=> fix(website: release selector): fix link to older versions

package.json, packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/PatternsStatus.js, packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/StatusFlag.js, packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/StatusFlag.test.js, packages/gatsby-theme-styleguide/src/templates/pattern-page.js, packages/gatsby-theme-styleguide/src/utils/status.js, src/docs/Foundations/AspectRatios/index.mdx, src/docs/Foundations/BorderRadius/index.mdx, src/docs/Foundations/Colors/index.mdx, src/docs/Foundations/Icons/index.mdx, src/docs/Foundations/Layout/Container/index.mdx, src/docs/Foundations/Layout/Grid/index.mdx, src/docs/Foundations/Layout/MarginAndPaddings/index.mdx, src/docs/Foundations/Layout/Responsive/index.mdx, src/docs/Foundations/MagicUnit/index.mdx, src/docs/Foundations/Shadows/index.mdx, src/docs/Foundations/Strokes/index.mdx, src/docs/Foundations/Typography/BodyStyles/index.mdx, src/docs/Foundations/Typography/Colors/index.mdx, src/docs/Foundations/Typography/FontFamilies/index.mdx, src/docs/Foundations/Typography/HeadingStyles/index.mdx, src/docs/Foundations/Typography/HeroStyles/index.mdx, src/docs/Foundations/Typography/ScaleAndSizes/index.mdx
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-253
=> feat(patterns/status): set stable patterns status and prep bêta release

packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js, packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/PatternStatusGroup.js, packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/__tests__/__snapshots__/PatternStatusGroup.js.snap, packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/__tests__/__snapshots__/patternStatus.js.snap, packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/StatusFlag.js, packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/StatusFlag.test.js, packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/__snapshots__/StatusFlag.test.js.snap, packages/gatsby-theme-styleguide/src/templates/pattern-page.js, yarn.lock
Header redesign
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-248
=> feat(website/header): header redesign

packages/gatsby-github-release/gatsby-node.js, packages/gatsby-theme-styleguide/src/gatsby-components/Changelog/Changelog.js, packages/gatsby-theme-styleguide/src/gatsby-components/Changelog/__tests__/Changelog.test.js, packages/gatsby-theme-styleguide/src/gatsby-components/Changelog/__tests__/__snapshots__/Changelog.test.js.snap, packages/gatsby-theme-styleguide/src/gatsby-components/Changelog/index.js, src/docs/Updates/PatternsStatus/index.mdx, src/docs/Updates/Updates/index.mdx
Github issue number or Jira issue URL: MZC-222 add changeling page in update
=> feat(onboard/updates): create changelog page

.github/githubRefToURL.sh, .github/workflows/push.yml, .github/workflows/release.yml, ci/deploy.js, packages/gatsby-theme-styleguide/src/gatsby-components/Highlight/Highlight.js, packages/gatsby-theme-styleguide/src/gatsby-components/Highlight/__tests__/Highlight.test.js, packages/gatsby-theme-styleguide/src/gatsby-components/Highlight/__tests__/__snapshots__/Highlight.test.js.snap, packages/gatsby-theme-styleguide/src/gatsby-components/Highlight/index.js, packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss, packages/gatsby-theme-styleguide/src/gatsby-components/layout.js, src/docs/Components/Buttons/code.mdx, src/docs/Foundations/Colors/index.mdx, src/docs/GetStarted/Designers/aboutTheSystem/index.mdx, src/docs/GetStarted/Designers/installation/index.mdx, src/docs/GetStarted/Designers/whatsIncluded/index.mdx, src/docs/GetStarted/Developers/CssNamingConventions/index.mdx, src/docs/GetStarted/Developers/CustomizeTokens/index.mdx, src/docs/GetStarted/Developers/configurePostCss/index.mdx, src/docs/GetStarted/Developers/configureStylelint/index.mdx, src/docs/GetStarted/Developers/whatsincluded/index.mdx
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-224
=> feat(website/highlights): create highlight components

packages/styles/layouts/_l.container.scss, src/docs/Foundations/Layout/Container/code.mdx, src/docs/Foundations/Layout/Container/index.mdx
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-268
=> feat(patterns/container): use LMFR‘s container as default one

src/docs/Components/TextInput/code.mdx, src/docs/Components/TextInput/index.mdx, src/docs/Components/TextInput/previews/input-invalid-state.preview.html, src/docs/Components/TextInput/previews/input-invalid.preview.html, src/docs/Components/TextInput/previews/input-small-left-icon.preview.html, src/docs/Components/TextInput/previews/input-small-state.preview.html, src/docs/Components/TextInput/previews/input-state.preview.html, src/docs/Components/TextInput/previews/left-icon-input.preview.html
[M-VUE] - Add pattern: Text input and update Text Input pattern on Mozaic
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-297
=> feat(patterns/text-input): update text-input component

src/docs/Foundations/Strokes/index.mdx
Github issue number or Jira issue URL: MZC-324
=> fix(patterns/strokes): remove typo

src/docs/Components/TextInput/code.mdx
Add pseudo-class :valid and :invalid for form elements
Github issue number or Jira issue URL: https://design-system-adeo.atlassian.net/browse/MZC-335
=> feat(patterns/input): update documentation about css pseudo-classes

packages/gatsby-theme-styleguide/gatsby-config.js, packages/gatsby-theme-styleguide/gatsby-node.js, packages/gatsby-theme-styleguide/gatsby-ssr.js, packages/gatsby-theme-styleguide/package.json, packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuHeader.js, packages/gatsby-theme-styleguide/src/gatsby-components/Search/Search.js, packages/gatsby-theme-styleguide/src/gatsby-components/Search/index.js, packages/gatsby-theme-styleguide/src/gatsby-components/SubContents/SubContents.js, packages/tokens/build/scss/_tokens.scss, src/docs/Components/Flags/index.mdx, yarn.lock
create a search engine for the documentation
=> feat(website/search): create search engine

src/docs/Components/Notification/index.mdx
Github issue number or Jira issue URL: MZC-345 (https://design-system-adeo.atlassian.net/browse/MZC-345?atlOrigin=eyJpIjoiNTkwZGU1MDJiYTYwNDI3Nzk5NGE3MWE3NWUzOWUyMzMiLCJwIjoiaiJ9)
=> fix(pattern/notifications): improve the notification requirements

README.md
=> chore(spellcheck): fix spellcheck error on the readme

packages/styles/components/_c.button.scss
Github issue number or Jira issue URL: 
https://github.com/adeo/mozaic-design-system/issues/497
=> fix(patterns/buttons): add pointer-events property on button label - #497

packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuHeader.js
QuickFix for the position of the current version of Mozaic.
=> fix(website/menu): correct the mozaic's version position

iconCompiler/componentsGenerators/__test__/__snapshots__/vueIcon.test.js.snap, iconCompiler/componentsGenerators/__test__/index.test.js, iconCompiler/componentsGenerators/vueIcon.js
=> fix(pattern/icon): generate only path on Vue component

src/docs/Contributing/Developers/InstallForDev/index.mdx, src/docs/GetStarted/Developers/Configuration/index.mdx, src/docs/GetStarted/Developers/configurePostCss/index.mdx, src/docs/GetStarted/Developers/configureStylelint/index.mdx, src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
Github issue number or Jira issue URL: **HOMEDESIGN Contribution**
=> fix(onboard/spellcheck): update stylelint occurrences (#508)

.github/PULL_REQUEST_TEMPLATE.md
Spellcheck and link fix on GitHub pr template
Github issue number or Jira issue URL: **HOMEGENIUS Contribution**
=> fix(chore/github-pr-template): spellcheck and link fix (#509)

package.json, yarn.lock
=> fix(chore/security): fix minimist and acorn vulnerabilities

packages/styles/settings-tools/_s.fonts-faces.scss, packages/styles/settings-tools/_s.headings.scss, packages/styles/typography/_t.headings.scss
Resolve #502
Correct some duplicate css rules
Github issue number or Jira issue URL: [ISSUE-552](https://github.com/adeo/mozaic-design-system/issues/502)
=> fix(patterns/headings): correct some duplicate css rules

packages/styles/components/_c.button.scss, packages/styles/settings-tools/_s.buttons.scss, packages/styles/settings-tools/_s.unstyle.scss
Remove some duplicate css rules
GitHub issue number or Jira issue URL: [ISSUE-503](https://github.com/adeo/mozaic-design-system/issues/503)
=> fix(patterns/buttons): remove some duplicate css rules

iconCompiler/componentsGenerators/__test__/__snapshots__/vueIcon.test.js.snap, iconCompiler/componentsGenerators/vueIcon.js, packages/icons/vue/index.vue
Quick fix - missing comma correction
=> fix(patterns/icons-vuejs): missing comma correction

packages/styles/components/_c.pagination.scss, src/docs/Components/Pagination/code.mdx, src/docs/Components/Pagination/previews/pagination-default.preview.html, src/docs/Components/Pagination/previews/pagination-light.preview.html, src/docs/Components/Pagination/previews/pagination.preview.html
=> refactor(patterns/pagination): update aria attribute on buttons

.github/workflows/push.yml, .github/workflows/release.yml
=> fix(chore): use adeo/httpie.action

package.json, yarn.lock
=> fix(chore/dependencies): fix security alert websocket-extensions

src/docs/Components/Buttons/index.mdx
=> refactor(patterns/button): improve neutral button documentation

package.json, yarn.lock
=> fix(chore): upgrade graphql-playground-html version

.github/workflows/push.yml, .github/workflows/release.yml
=> fix(chore): update api token

src/docs/Foundations/BorderRadius/code.mdx
Resolves #573
Update code documentation
GitHub issue number or Jira issue URL: [ISSUE-573](https://github.com/adeo/mozaic-design-system/issues/573)
=> feat(patterns/border-radius): update code documentation

src/docs/Components/Tabs/design.mdx
=> fix(patterns/tabs): remove typo

packages/styles/components/_c.tooltip.scss, packages/styles/settings-tools/_s.inline-icons.scss, src/docs/Components/Tooltip/code.mdx, src/docs/Components/Tooltip/index.mdx, src/docs/Components/Tooltip/previews/default.preview.html, src/docs/Components/Tooltip/previews/default.preview.scss, src/docs/Components/Tooltip/specs.mdx
=> feat(pattern/tooltip): add tooltip pattern and documentation

packages/styles/components/_c.breadcrumb.scss, packages/styles/settings-tools/_s.inline-icons.scss, src/docs/Components/Breadcrumb/code.mdx, src/docs/Components/Breadcrumb/index.mdx, src/docs/Components/Breadcrumb/previews/dark-mode.preview.html, src/docs/Components/Breadcrumb/previews/dark-mode.preview.scss, src/docs/Components/Breadcrumb/previews/default.preview.html, src/docs/Components/Breadcrumb/previews/default.preview.scss, src/docs/Components/Breadcrumb/previews/mobile.preview.html, src/docs/Components/Breadcrumb/previews/mobile.preview.scss, src/docs/Components/Breadcrumb/previews/responsive.preview.html, src/docs/Components/Breadcrumb/previews/responsive.preview.scss
Add pattern Breadcrumb
GitHub issue number or Jira issue URL: [ID-1371](https://adeo.kanbanize.com/ctrl_board/10/cards/1371/details/)
=> feat(patterns/breadcrumb): add breadcrumb pattern

packages/styles/components/_c.fields.scss, packages/styles/components/_c.toggle.scss, src/docs/Components/Form/Checkbox/code.mdx, src/docs/Components/Form/Checkbox/index.mdx, src/docs/Components/Form/Checkbox/previews/group-inline.preview.html, src/docs/Components/Form/Radio/code.mdx, src/docs/Components/Form/Radio/index.mdx, src/docs/Components/Form/Radio/previews/group-inline.preview.html, src/docs/Components/Form/Toggle/code.mdx, src/docs/Components/Form/Toggle/previews/group-inline.preview.html
Resolves #609
ISSUE : forms components (radio/checkbox/toggle)
GitHub issue number or Jira issue URL: [ISSUE-609](https://github.com/adeo/mozaic-design-system/issues/609)
=> fix(patterns/form): fix inline form behaviour on mobile

package.json, yarn.lock
=> fix(chore): update admzip to fix error 79 on Catalina OS

packages/tokens/build/ios/StyleDictionaryColor.swift
Resolves #624
Fix issue 624
GitHub issue number or Jira issue URL: [Issue-624](https://github.com/adeo/mozaic-design-system/issues/624)
=> fix(tools/tokens): update swift colors tokens

packages/styles/typography/_t.headings.scss, src/docs/Foundations/Typography/HeadingStyles/code.mdx, src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeading-underlines.preview.html
Fix alignment responsive modifiers
GitHub issue number or Jira issue URL: [ISSUE-623](https://github.com/adeo/mozaic-design-system/issues/623)
=> fix(patterns/headings): fix responsive modifiers alignment

packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/TableOfContents.js, packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss
Improve Table Of Content
GitHub issue number or Jira issue URL: [ID-5542](https://adeo.kanbanize.com/ctrl_board/10/cards/5542/details/)
=> refactor(website/toc): improve table of content styles

packages/gatsby-theme-styleguide/src/gatsby-components/JSImplementation/JSImplementation.js, src/docs/Components/Accordion/index.mdx, src/docs/Components/Breadcrumb/index.mdx, src/docs/Components/Buttons/index.mdx, src/docs/Components/Dividers/index.mdx, src/docs/Components/FileUploader/index.mdx, src/docs/Components/Flags/index.mdx, src/docs/Components/Form/Checkbox/index.mdx, src/docs/Components/Form/Field/index.mdx, src/docs/Components/Form/Radio/index.mdx, src/docs/Components/Form/Select/index.mdx, src/docs/Components/Form/TextArea/index.mdx, src/docs/Components/Form/TextInput/index.mdx, src/docs/Components/Form/Toggle/index.mdx, src/docs/Components/Links/index.mdx, src/docs/Components/Modals/index.mdx, src/docs/Components/Notification/index.mdx, src/docs/Components/Pagination/index.mdx, src/docs/Components/RatingStars/index.mdx, src/docs/Components/Tabs/index.mdx, src/docs/Components/Tag/index.mdx, src/docs/Components/Tooltip/index.mdx
=> feat(website/header): add data for status and js link

packages/gatsby-theme-styleguide/src/gatsby-components/CalloutVue/CalloutVue.js, packages/gatsby-theme-styleguide/src/gatsby-components/CalloutVue/index.js, packages/gatsby-theme-styleguide/src/gatsby-components/JSImplementation/JSImplementation.js, packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js, packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/PatternStatusGroup.js, packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/__tests__/__snapshots__/PatternStatusGroup.js.snap, packages/gatsby-theme-styleguide/src/templates/pattern-page.js
=> feat(website/calloutvue): display vuejs link in code tab

packages/styles/components/_c.hero.scss, src/docs/Components/Hero/code.mdx, src/docs/Components/Hero/index.mdx, src/docs/Components/Hero/previews/box.preview.html, src/docs/Components/Hero/previews/box.preview.scss, src/docs/Components/Hero/previews/boxFull.preview.html, src/docs/Components/Hero/previews/boxFull.preview.scss
=> feat(pattern/hero): add box hero modifier

package.json
=> fix(dev-infra): upgrade packages versions

packages/styles/components/_c.toggle.scss, packages/styles/settings-tools/_s.toggle.scss, src/docs/Components/Form/Toggle/index.mdx, src/docs/Components/Form/Toggle/previews/toggle-default-2lines.preview.html, src/docs/Components/Form/Toggle/previews/toggle-default-2lines.preview.scss
=> fix(patterns/toggle): increase line-height

src/docs/Contributing/SubmitChanges/SubmitNewPattern/index.mdx
=> fix(onboard): repair broken link

README.md
=> feat(docs): upgrade readme 

packages/gatsby-theme-styleguide/src/components/Header/Header.js, packages/gatsby-theme-styleguide/src/gatsby-components/JSImplementation/JSImplementation.js, packages/gatsby-theme-styleguide/src/gatsby-components/Search/Search.js, packages/gatsby-theme-styleguide/src/pages/index.js
=> fix(website/component): fix warning from website component

package.json
=> feat(tools/versionning): remove beta and use semver versionning

packages/styles/settings-tools/_s.text-input.scss
Add height property to the input field
=> feat(patterns/input): add height property to the input field

src/docs/Components/Flags/code.mdx
Resolves #688
GitHub issue number or Jira issue URL: [ISSUE-688](https://github.com/adeo/mozaic-design-system/issues/688)
=> fix(onboard/flag): update flag component code documentation

packages/styles/components/_c.breadcrumb.scss, packages/styles/settings-tools/_s.inline-icons.scss, src/docs/Components/Breadcrumb/accessibility.mdx, src/docs/Components/Breadcrumb/code.mdx, src/docs/Components/Breadcrumb/previews/responsive.preview.html
Fix #689
Improve breadcrumb behavior on mobile resolutions
GitHub issue number or Jira issue URL: [Issue-689](https://github.com/adeo/mozaic-design-system/issues/689)
=> fix(patterns/breadcrumb): improve breadcrumb behavior on mobile resolutions

src/docs/Components/Accordion/accessibilty.mdx, src/docs/Components/Accordion/code.mdx, src/docs/Components/Accordion/previews/basic.preview.html, src/docs/Components/Accordion/previews/basic.preview.scss, src/docs/Components/Accordion/previews/disable.preview.html, src/docs/Components/Accordion/previews/disable.preview.scss, src/docs/Components/Accordion/previews/icon.preview.html, src/docs/Components/Accordion/previews/icon.preview.scss, src/docs/Components/Accordion/previews/no-padding.preview.html, src/docs/Components/Accordion/previews/no-padding.preview.scss, src/docs/Components/Accordion/previews/open.preview.html, src/docs/Components/Accordion/previews/open.preview.scss, src/docs/Components/Accordion/previews/stacked.preview.html, src/docs/Components/Accordion/previews/stacked.preview.scss, src/docs/Components/Accordion/previews/states.preview.html, src/docs/Components/Accordion/previews/states.preview.scss
Update accessibility information
=> refactor(onboard/accordion): update accessibility information

src/docs/Foundations/Layout/Container/code.mdx, src/docs/Foundations/Layout/Container/index.mdx
Improve container documentation
=> refactor(onboard/container): improve container documentation

src/docs/Components/Hero/code.mdx
Improve the documentation of the Hero component in order to make the behavior of the boxedcontent more understandable.
=> refactor(onboard/hero): improve hero documentation

ci/docker-wait/Dockerfile
=> fix(chore/docker): use version 20.3.3 for pip

src/docs/GetStarted/Developers/Installation/postcss.mdx
**Update PostCSS documentation for Angular**
=> refactor(onboard/postcss): update PostCSS documentation for Angular

packages/styles/components/_c.accordion.scss
Fix #729
GitHub issue number or Jira issue URL: Fix [ISSUE-729](https://github.com/adeo/mozaic-design-system/issues/729)
=> feat(patterns/accordion): add focus when keyboard navigation

packages/styles/settings-tools/_s.fonts-faces.scss
Resolves #736
Add `font-display: swap;` on `@font-face` declarations in order to improve fonts loading performance
GitHub issue number or Jira issue URL: [ISSUE-736](https://github.com/adeo/mozaic-design-system/issues/736)
=> feat(foundations/fonts): add font-display:swap on @font-face declarations

package.json, yarn.lock
=> chore(deps): bump axios from 0.19.0 to 0.21.1

src/docs/Components/Buttons/code.mdx, src/docs/Components/Buttons/previews/basic.preview.html, src/docs/Components/Buttons/previews/button-icon-and-text.preview.html, src/docs/Components/Buttons/previews/button-icon-only.preview.html, src/docs/Components/Buttons/previews/button-icon-position.preview.html, src/docs/Components/Buttons/previews/button-icon.preview.html, src/docs/Components/Buttons/previews/button-proximity-dont.preview.html, src/docs/Components/Buttons/previews/button-sizes.preview.html, src/docs/Components/Buttons/previews/button-state.preview.html, src/docs/Components/Buttons/previews/button-styles.preview.html, src/docs/Components/Buttons/previews/button-widths-responsive.preview.html, src/docs/Components/Buttons/previews/button-widths.preview.html, src/docs/Components/Buttons/previews/intro-bordered.preview.html, src/docs/Components/Buttons/previews/intro.preview.html, src/docs/Components/Buttons/previews/suportedMarkup.preview.html
Update of the previews code
GitHub issue number or Jira issue URL: [ID-13805](https://adeo.kanbanize.com/ctrl_board/10/cards/13805/details/)
=> refactor(patterns/button): update of the previews code

packages/css-dev-tools/postcssPluginConfig.js
GitHub issue number or Jira issue URL: [ISSUE-553](https://github.com/adeo/mozaic-design-system/issues/553)
=> chore(postcss): log env variable used

src/docs/Components/Links/code.mdx
=> fix(onboard/link): fix the documentation of the link mixin

packages/css-dev-tools/package.json, packages/css-dev-tools/postcssPluginConfig.js, packages/styles/components/_c.accordion.scss, packages/styles/components/_c.breadcrumb.scss, packages/styles/components/_c.fields.scss, packages/styles/components/_c.hero.scss, packages/styles/components/_c.layer.scss, packages/styles/components/_c.left-icon-input.scss, packages/styles/components/_c.modal.scss, packages/styles/components/_c.notification.scss, packages/styles/components/_c.pagination.scss, packages/styles/components/_c.progressbar.scss, packages/styles/components/_c.quantity-selector.scss, packages/styles/components/_c.stars-input.scss, packages/styles/components/_c.stars-result.scss, packages/styles/components/_c.tabs.scss, packages/styles/components/_c.tooltip.scss, packages/styles/settings-tools/_all-settings.scss, packages/styles/settings-tools/_t.selectors.scss, packages/styles/typography/_t.headings.scss, src/docs/Components/Layers/code.mdx, src/docs/Components/Layers/previews/border-scroll-bar.preview.html, src/docs/Components/Layers/previews/border-scroll-bar.preview.scss, src/docs/Components/RatingStars/previews/stars-result-all-sizes.preview.scss, yarn.lock
Fix #721
Add a sass function allowing to select the parent selector of Mozaic components.
GitHub issue number or Jira issue URL: **Fix** #721 
Example of implementation : http://fixissue721.demo.mozaic-design-system-dtrp.appspot.com/previews/Components/RatingStars/previews/stars-result-all-sizes.html
=> feat(tools/sass): add a sass function to get the parent selector

LICENSE
=> chore(license): add MIT license for Mozaic

lerna.json, package.json, yarn.lock
**Upgrade Lerna version to 4.0.0**
=> chore(deps/lerna): upgrade Lerna version to 4.0.0

.prettierrc, package.json, yarn.lock
**Upgrade prettier version to >=2.2.1**
=> chore(deps/prettier): upgrade prettier version to >=2.2.1

package.json, yarn.lock
**Upgrade resolutions dependencies**
=> chore(deps): upgrade resolutions dependencies

ci/docker-wait/Dockerfile
=> chore(ci): fix google-cloud-sdk version

package.json, yarn.lock
=> chore(deps): upgrade deps for security reason

package.json, yarn.lock
=> chore(deps/lint-staged): upgrade lint-staged version

src/docs/Updates/Roadmap/index.mdx
=> feat(onboard): update roadmap

packages/styles/layouts/_l.flexy.scss, yarn.lock
**Update ml-flexy__col--initial behaviour**
=> fix(layout/grid): update ml-flexy__col--initial behaviour

ci/docker-wait/Dockerfile
=> chore(ci): use python3 and pip3 version

packages/styles/layouts/_l.flexy.scss
Quick refactor of `--grow` modifier, before release.
=> refactor(layout/grid): update --grow modifier mixin

app.demo.yaml, app.yaml
=> feat(website): redirect to https

src/docs/Components/Accordion/index.mdx, src/docs/Components/Breadcrumb/index.mdx, src/docs/Components/Dividers/index.mdx, src/docs/Components/Flags/index.mdx, src/docs/Components/Form/Datepicker/index.mdx, src/docs/Components/Form/Field/index.mdx, src/docs/Components/Form/QuantitySelector/index.mdx, src/docs/Components/Form/Radio/index.mdx, src/docs/Components/Form/Select/index.mdx, src/docs/Components/Form/TextArea/index.mdx, src/docs/Components/Form/TextInput/index.mdx, src/docs/Components/Form/Toggle/index.mdx, src/docs/Components/Hero/index.mdx, src/docs/Components/Layers/index.mdx, src/docs/Components/Links/index.mdx, src/docs/Components/Modals/index.mdx, src/docs/Components/Notification/index.mdx, src/docs/Components/Pagination/index.mdx, src/docs/Components/ProgressBar/index.mdx, src/docs/Components/RatingStars/index.mdx, src/docs/Components/Tabs/index.mdx, src/docs/Components/Tag/index.mdx, src/docs/Components/Tooltip/index.mdx, src/docs/Foundations/Typography/HeadingStyles/index.mdx
=> refactor(website/status): update figma status

packages/styles/settings-tools/_s.focus.scss
**focus - fix pseudo-element behaviour**
=> fix(patterns): focus - fix pseudo-element behaviour

src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
- List the Mozaic NPM mandatory
- Use --save-dev flag when installing postcss-cli
- Solve a stylelint issue in the bundle.scss file
=> fix: review the Getting Started tutorial

packages/styles/components/_c.phone-number.scss
=> fix(phonenumber): add white background for list

src/docs/GetStarted/Developers/CustomizeTokens/adeoPreset.mdx, src/docs/GetStarted/Developers/CustomizeTokens/index.mdx
**Improve documentation about tokens customization**
=> refactor(onboard/tokens): improve documentation about tokens customization

packages/styles/components/_c.progressbar.scss, packages/styles/settings-tools/_s.progressbar.scss, src/docs/Components/ProgressBar/code.mdx, src/docs/Components/ProgressBar/previews/variations-sizes.preview.html
=> feat(pattern/progressbar): add new size variation - xs variation

packages/styles/components/_c.progressbar.scss, src/docs/Components/ProgressBar/code.mdx, src/docs/Components/ProgressBar/previews/branded.preview.html, src/docs/Components/ProgressBar/previews/default.preview.html, src/docs/Components/ProgressBar/previews/percentage-half.preview.html, src/docs/Components/ProgressBar/previews/percentage.preview.html, src/docs/Components/ProgressBar/previews/variations-colors.preview.html, src/docs/Components/ProgressBar/previews/variations-sizes.preview.html
=> refactor(patterns/progressbar): code & documentation refactor

packages/css-dev-tools/postcssPluginConfig.js
Add missing paths to the const basePaths
=> fix(tools/css-dev-tools): add missing paths to the const basePaths

packages/styles/components/_c.stepper.scss
**Use the new math.div() function for divisions inside the Stepper scss file**
=> refactor(patterns/stepper): use the new math.div() function for divisions

packages/css-dev-tools/styleLintConfig.js, yarn.lock
**Turn of the rule 'no-invalid-position-at-import-rule'**
=> fix(tools/stylelint): turn of the rule 'no-invalid-position-at-import-rule'

src/docs/GetStarted/Developers/Installation/postcss.mdx
Update PostCSS x Vue.js documentation
=> refactor(docs/vue.js): update PostCSS x Vue.js documentation 

packages/styles/utilities/_u.scroll.scss, src/docs/Components/Layers/code.mdx, src/docs/Components/Modals/code.mdx
Add a css utility class to prevent body from scrolling
=> feat(styles/utilities): add a css utility class to prevent body from scrolling

packages/styles/settings-tools/_s.text-input.scss
=> fix(patterns/text-input): update the line-height & paddings of the component

packages/styles/components/_c.password-input.scss, src/docs/Components/Form/PasswordInput/accessibilty.mdx, src/docs/Components/Form/PasswordInput/code.mdx, src/docs/Components/Form/PasswordInput/index.mdx, src/docs/Components/Form/PasswordInput/previews/all-cases.preview.html, src/docs/Components/Form/PasswordInput/previews/all-cases.preview.scss, src/docs/Components/Form/PasswordInput/previews/default.preview.html, src/docs/Components/Form/PasswordInput/previews/default.preview.scss
Add new **Password Input** component
GitHub issue number or Jira issue URL: https://jira.adeo.com/browse/MZC-3
=> feat(patterns/passwordinput): add code and associated documentation

packages/styles/components/_c.stepper.scss, packages/styles/settings-tools/_s.stepper.scss, src/docs/Components/Stepper/code.mdx, src/docs/Components/Stepper/index.mdx, src/docs/Components/Stepper/previews/compact.preview.html, src/docs/Components/Stepper/previews/compact.preview.scss, src/docs/Components/Stepper/previews/three-and-more.preview.html, src/docs/Components/Stepper/previews/up-to-three.preview.html
Add new **compact** variation
GitHub issue number or Jira issue URL: https://jira.adeo.com/browse/MZC-101
=> feat(patterns/stepper): add new 'compact' variation

packages/styles/layouts/_l.flexy.scss
=> feat(flex): add missing justify modifier

packages/styles/components/_c.toggle.scss, packages/styles/settings-tools/_s.toggle.scss, src/docs/Components/Form/Toggle/previews/toggle-extend-sizes.preview.html
=> fix(patterns/toggle): update the label padding value from mixin

packages/gatsby-theme-styleguide/src/components/McToggle/McToggle.js, packages/styles/components/_c.toggle.scss
=> fix(patterns/toggle): add missing classes

src/docs/Contributing/Principles/Glossary/index.mdx
Reorder the glossary alphabetically
=> refactor(onboard/glossary): reorder the glossary alphabetically

packages/gatsby-theme-styleguide/src/components/Header/Header.js
=> fix(logo): change view box for logo

src/docs/Help/Help/index.mdx
=> docs(website/contact): improve contact page

src/docs/Components/Heading/index.mdx
=> docs(component/heading): remove unecessary text

yarn.lock
=> chore(dependencies): upgrade outdated dependencies

packages/gatsby-theme-styleguide/src/gatsby-components/Menu/Menu.js
=> docs(menu): limit to last 20 versions

app.demo.yaml, app.yaml
=> chore(secu): add http header

src/docs/Components/Modals/index.mdx, src/docs/Components/Modals/previews/delete-action.preview.html, src/docs/Components/Modals/previews/delete-action.preview.scss
=> docs(components/modal): add delete action variation

app.demo.yaml
=> docs(build): remove unnecessary secu rules for PR

app.yaml
=> fix(release): remove duplicate from app.yaml

app.yaml
=> chore(deploy): add csp url

packages/icons/react/index.d.ts
=> feat(icons): add typescript to react icons

src/docs/Foundations/Colours/adeo.mdx, src/docs/Foundations/Colours/index.mdx
=> docs(colours): add link to adeo preset

packages/css-dev-tools/postcssPluginConfig.js, packages/gatsby-theme-styleguide/gatsby-node.js, packages/gatsby-theme-styleguide/src/gatsby-components/SiteMapData/SiteMapData.js
Use `fs.mkdir` instead of `mkdirp`
=> fix(deps/mkdirp): use fs.mkdir instead of mkdirp

packages/styles/components/_c.layer.scss, src/docs/Components/Layers/previews/cta-link.preview.scss, src/docs/Components/Layers/previews/cta-two.preview.scss, src/docs/Components/Layers/previews/default.preview.scss, src/docs/Components/Layers/previews/extended.preview.scss, src/docs/Components/Layers/previews/header-with-icon.preview.scss, src/docs/Components/Layers/previews/without-footer.preview.scss
Resolves #978
Update the padding value of the `.mc-layer__content` element
=> feat(components/layer): update the padding value of the `.mc-layer__content` element

packages/css-dev-tools/styleLintConfig.js, yarn.lock
Turn off the rule `max-line-length`
=> fix(tools/stylelint): turn off the rule `max-line-length`

src/docs/Foundations/Colours/adeo.mdx, src/docs/GetStarted/Developers/CustomizeTokens/adeoPreset.mdx
=> docs(colours): add link from the preset doc to the colour doc

packages/styles/generic/_g.reset.scss
Add `hidden` attribute
GitHub issue number or Jira issue URL: 
Solve in part => https://github.com/adeo/mozaic-freemarker/issues/161
=> feat(generic/reset): add [hidden] attribute in the css reset

packages/tokens/AdeoProperties/color/button.json, packages/tokens/AdeoProperties/color/flag.json, packages/tokens/AdeoProperties/color/link.json
Update of ADEO colours for buttons, flags & links
=> feat(tools/tokens): update of ADEO colours for buttons, flags & links

src/docs/Components/ListBox/previews/default.preview.html
=> fix(listbox): clean broken preview

packages/styles/components/_c.listbox.scss
=> fix(listbox): enhance left opening

packages/styles/package.json
Update `@mozaic-ds/tokens` version to **2.0.0-rc.2**
=> chore(dependencies): update `@mozaic-ds/tokens` version to 2.0.0-rc.2

src/docs/Components/Flags/previews/bordered.preview.html, src/docs/Components/Flags/previews/flag-all.preview.html, src/docs/Components/Flags/previews/solid.preview.html
=> docs(refactor/flags): update HTML code in previews

packages/tokens/properties/color/notification.json
Update the color of the notification icons
=> fix(pattern/colors): update the color of the notification icons

packages/styles/components/_c.phone-number.scss, src/docs/Components/Form/PhoneNumberInput/previews/basic.preview.html, src/docs/Components/Form/PhoneNumberInput/previews/label.preview.html, src/docs/Components/Form/PhoneNumberInput/previews/opened.preview.html
=> feat(phonenumber): use emoji flags

packages/styles/components/_c.modal.scss
Resolves https://github.com/adeo/mozaic-design-system/issues/1149
=> fix(modal): use fill-available

packages/styles/layouts/_l.flexy.scss
=> fix(grid): enhance loop to remove stylelint issue

packages/styles/components/_c.accordion.scss, packages/styles/settings-tools/_s.accordions.scss, yarn.lock
Improve styles to handle nested accordions
GitHub issue number or Jira issue URL:
https://github.com/adeo/mozaic-react/issues/104
=> fix(component/accordion): improve styles to handle nested accordions

iconCompiler/generateIconsJS/iconsModules.js, packages/icons/js/icons.js
=> feat(icons): add id type for logos

packages/tokens/BricomanProperties/color/button.json, packages/tokens/BricomanProperties/color/heading.json
Bricoman - update tokens for buttons & headings
=> fix(tools/tokens): Bricoman - update tokens for buttons & headings

packages/styles/components/_c.layer.scss
Improve the scoping of the `is-open` state class
=> fix(component/layer): Improve the scoping of the `is-open` state class

packages/styles/components/_c.tabs.scss
Add `pointer-events: none;` on `.mc-tabs__text` element
=> fix(component/tabs): add `pointer-events: none;` on `.mc-tabs__text` element

iconCompiler/generateIconsJS/index.js, packages/icons/js/icons.common.d.ts, packages/icons/js/icons.d.ts, packages/icons/svelte/icons.js
=> fix(icons): add typescript for common

packages/styles/components/_c.accordion.scss, packages/styles/settings-tools/_s.accordions.scss, packages/styles/settings-tools/_s.unstyle.scss, src/docs/Components/Accordion/previews/basic.preview.html, src/docs/Components/Accordion/previews/basic.preview.scss
Improve trigger button styles for scoped modules
=> fix(component/accordion): improve trigger button styles for scoped modules

.github/workflows/release.yml
=> chore(action): downgrade appengine version

packages/styles/components/_c.badge.scss, packages/styles/settings-tools/_s.badges.scss
`line-height` update + code improvement
=> style(component/badge): line-height update + code improvement

packages/styles/components/_c.button.scss, packages/styles/components/_c.pagination.scss, src/docs/Components/Pagination/previews/pagination-compact.preview.html, src/docs/Components/Pagination/previews/pagination-compact.preview.scss, src/docs/Components/Pagination/previews/pagination-default.preview.html, src/docs/Components/Pagination/previews/pagination-default.preview.scss, src/docs/Components/Pagination/previews/pagination.preview.html, src/docs/Components/Pagination/previews/pagination.preview.scss
=> feat(pagination): use button rather than specific classes

packages/styles/components/_c.stars-input.scss
Fix the display of stars in `s`, `l` & `xl` variations
=> fix(component/starsinput): fix the display of stars in `s`, `l` & `xl` variations

packages/styles/components/_c.card.scss
Improve content space & fluid variation
=> style(component/card): improve content space & fluid variation

README.md, package.json, packages/gatsby-theme-styleguide/package.json, packages/postcss-media-queries-packer-on-demand/package.json, packages/postcss-prepend/package.json, packages/stylelint-plugin-mozaic/package.json, packages/styles/package.json, packages/tokens/package.json, src/docs/GetStarted/Developers/Installation/import.mdx, src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
=> chore(package): clean package.json

package.json
Update npm script to release rc
=> build(npm/scripts): update npm script to release rc

packages/styles/components/_c.autocomplete.scss, packages/styles/components/_c.dropdown.scss, src/docs/Components/Form/Autocomplete/previews/default.preview.html, src/docs/Components/Form/Autocomplete/previews/default.preview.scss, src/docs/Components/Form/Autocomplete/previews/multi.preview.scss, src/docs/Components/Form/Dropdown/previews/default.preview.html, src/docs/Components/Form/Dropdown/previews/default.preview.scss, src/docs/Components/Form/Dropdown/previews/invalid.preview.scss
Update the position of the loader
=> feat(component/autocomplete-dropdown): update the position of the loader

src/docs/Components/Accordion/index.mdx, src/docs/Components/DataTable/index.mdx, src/docs/Components/Form/Autocomplete/index.mdx, src/docs/Components/Form/Dropdown/index.mdx, src/docs/Components/Form/PasswordInput/index.mdx, src/docs/Components/Form/PhoneNumberInput/index.mdx, src/docs/Components/Heading/index.mdx, src/docs/Components/Layers/index.mdx, src/docs/Components/ListBox/index.mdx, src/docs/Components/Loader/index.mdx, src/docs/Components/Modals/index.mdx, src/docs/Components/OptionGroup/OptionButton/index.mdx, src/docs/Components/OptionGroup/OptionCard/index.mdx, src/docs/Components/Pagination/index.mdx, src/docs/Components/RatingStars/index.mdx, src/docs/Components/Stepper/index.mdx, src/docs/Components/Tabs/index.mdx, src/docs/Components/Tag/index.mdx
=> docs(links): update links

packages/stylelint-plugin-mozaic/package.json, yarn.lock
Resolves #1252
Remove unused `postcss-bem-linter` plugin
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-design-system/issues/1252
=> feat(tools/stylelint-plugin-mozaic): remove unused `postcss-bem-linter` plugin

packages/styles/components/_c.option-card.scss, src/docs/Components/OptionGroup/OptionCard/code.mdx, src/docs/Components/OptionGroup/OptionCard/previews/product.preview.scss
Update the `z-index` values of the component elements
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-design-system/issues/1318
=> fix(component/option-card): update the `z-index` values of the component elements

packages/styles/components/_c.toggle.scss
=> fix(toggle): use background-position 

packages/styles/components/_c.tabs.scss
=> fix(tabs): centered element for all sizes

packages/styles/components/_c.stepper.scss
=> fix(stepper): upgrade stepper code to latest

packages/css-dev-tools/sassConfig.js
Include the `preset` name in the `tokensPath`
=> feat(tools/tokens): include the `preset` name in the `tokensPath`

packages/gatsby-theme-styleguide/src/gatsby-components/IconViewer/IconTile.js, packages/gatsby-theme-styleguide/src/gatsby-components/IconViewer/IconViewer.js, packages/gatsby-theme-styleguide/src/gatsby-components/IconViewer/styles.scss
Add search functionality to filter icons
=> feat(icons): add search for icons list

packages/styles/components/_c.fields.scss, src/docs/Components/Form/Checkbox/previews/group-help-light.preview.html, src/docs/Components/Form/Checkbox/previews/group-help-text.preview.html, src/docs/Components/Form/Checkbox/previews/group-indeterminate.preview.html, src/docs/Components/Form/Checkbox/previews/group-inline.preview.html, src/docs/Components/Form/Checkbox/previews/group-invalid-light.preview.html, src/docs/Components/Form/Checkbox/previews/group-invalid.preview.html, src/docs/Components/Form/Checkbox/previews/group-requirement-light.preview.html, src/docs/Components/Form/Checkbox/previews/group-requirement.preview.html
Make legend optional
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-vue/issues/1103
Related to https://github.com/adeo/mozaic-vue/pull/1106
=> fix(component/field-group): make legend optional

packages/tokens/AdeoProperties/color/tooltip.json
Updating the Tooltip component tokens (preset Adeo)
=> feat(tools/tokens): adeo - updating the Tooltip component tokens

packages/styles/components/_c.file-uploader.scss, packages/styles/components/_c.notification.scss, packages/styles/components/_c.toggle.scss
=> fix(chrome): add background-size to display icons

packages/styles/components/_c.file-uploader.scss
report fix styles coming from Mozaic-Vue
=> feat(component/fileuploader): report fix styles coming from mozaic-vue

packages/styles/components/_c.autocomplete.scss
Add styles for the error message
=> feat(component/autocomplete): add styles for the error message

packages/styles/components/_c.button.scss, packages/styles/settings-tools/_s.buttons.scss
=> fix(button): remove pointer-event from disable button

packages/styles/components/_c.toggle.scss, src/docs/Components/Form/Toggle/previews/Toggle-item.preview.scss
Resolves #1401
Improve toggle component for scoped modules
GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-design-system/issues/1401
=> feat(component/toggle): improve toggle component for scoped modules

src/docs/Components/Notification/accessibility.mdx, src/docs/Components/Notification/previews/notification-success.preview.html, src/docs/Components/Notification/previews/notification-types.preview.html, src/docs/Components/Notification/previews/notification-variations.preview.html, src/docs/Components/Notification/previews/notification-warning.preview.html, src/docs/Components/Notification/previews/notification.preview.html, src/docs/Components/Notification/previews/sizes.preview.html, src/docs/Components/Notification/previews/with-buttons-usage.preview.html, src/docs/Components/Notification/previews/with-buttons.preview.html
=> feat(notification): add role status

packages/styles/components/_c.autocomplete.scss, packages/styles/components/_c.dropdown.scss, src/docs/Components/Form/Autocomplete/previews/default.preview.html, src/docs/Components/Form/Autocomplete/previews/invalid.preview.html, src/docs/Components/Form/Autocomplete/previews/multi.preview.html, src/docs/Components/Form/Dropdown/previews/default.preview.html, src/docs/Components/Form/Dropdown/previews/invalid.preview.html, src/docs/Components/Form/Dropdown/previews/multi.preview.html
Improve the display of the loader & the clear button
=> feat(component/autocomplete-dropdown): improve the display of the loader & the clear button

packages/tokens/BricomanProperties/size/font.json
=> feat(font-size): update font size 07 to 24px

.github/workflows/push.yml, .github/workflows/release.yml
[google-github-actions/auth](https://github.com/google-github-actions/auth) & [google-github-actions/deploy-appengine](https://github.com/google-github-actions/deploy-appengine) actions updated to use [Workload Identity Federation](https://cloud.google.com/iam/docs/workload-identity-federation) based authentication
=> ci(github/actions): implement GCP WIF authentication

.gcloudignore
Update `.gcloudignore` file to exclude cache files
=> ci(gcp/appengine): update `.gcloudignore` file to exclude cache files

.github/workflows/push.yml, .github/workflows/release.yml
Display the site url on the deployed environment
=> ci(gha/gcp): display the site url on the deployed environment

lerna.json, package.json
=> chore(lerna): remove useWorkspace and bootstrap

package.json, yarn.lock
=> chore(deps): add babel deps

packages/styles/components/_c.tooltip.scss
=> feat(tooltip): add word break modifier

packages/styles/components/_c.fields.scss
=> fix(field): add element class for inline

src/docs/Foundations/Content design/Principles/index.mdx, src/docs/Foundations/Content design/index.mdx
=> feat(docs): add content design principles

packages/styles/components/_c.segmented-control.scss
=> fix(segmented): add box-sizing

packages/styles/components/_c.action-bar.scss, packages/styles/components/_c.bottom-bar.scss, packages/styles/components/_c.stepper-bar.scss, src/docs/Components/BottomBar/ActionBar/code.mdx, src/docs/Components/BottomBar/ActionBar/index.mdx, src/docs/Components/BottomBar/ActionBar/previews/default.preview.html, src/docs/Components/BottomBar/ActionBar/previews/default.preview.scss, src/docs/Components/BottomBar/ActionBar/previews/fixed.preview.html, src/docs/Components/BottomBar/ActionBar/previews/fixed.preview.scss, src/docs/Components/BottomBar/ActionBar/previews/loading.preview.html, src/docs/Components/BottomBar/ActionBar/previews/loading.preview.scss, src/docs/Components/BottomBar/StepperBar/code.mdx, src/docs/Components/BottomBar/StepperBar/index.mdx, src/docs/Components/BottomBar/StepperBar/previews/default.preview.html, src/docs/Components/BottomBar/StepperBar/previews/default.preview.scss, src/docs/Components/BottomBar/StepperBar/previews/fixed.preview.html, src/docs/Components/BottomBar/StepperBar/previews/fixed.preview.scss, src/docs/Components/BottomBar/index.mdx
=> feat(bottom-bar): add code component

packages/styles/components/_c.segmented-control.scss
=> feat(segmented): add no-wrap modifier

packages/styles/components/_c.listbox.scss
Adjust the behaviour of listbox (actions)
=> fix(component/listbox): adjust behaviour of listbox (actions)

packages/gatsby-theme-styleguide/src/components/Story/Story.js, src/docs/Components/ListBox/code.mdx, src/docs/Components/ListBox/index.mdx
=> docs(listbox): update story links

gatsby-config.mjs, package.json, packages/gatsby-theme-styleguide/src/pages/{mdx.fields__slug}.js, yarn.lock
Add Gatsby plugins to manage sitemap & canonical links
=> docs(gatsby/seo): add Gatsby plugins to manage sitemap & canonical links

static/robots.txt
=> docs(gatsby/seo): add robots.txt

packages/styles/components/_c.listbox.scss
Update the `danger` state of listbox actions
=> fix(component/listbox): update the `danger` state of listbox actions

static/robots.txt
=> chore(robots): clean robot sitemap url

.github/CODEOWNERS
=> chore(codeowner): add codeowners file

packages/styles/components/_c.accordion.scss
Remove default white background
GitHub issue number or Jira issue URL:
Fix #1539
=> fix(component/accordion): remove default white background

packages/styles/components/_c.menu.scss
=> feat(menu): use auto for menu width

packages/styles/components/_c.datatable-tools.scss
Remove not necessary class `mc-datatable__expand`
=> feat(component/datatable): remove not necessary class `mc-datatable__expand`

packages/styles/components/_c.datatable.scss, packages/styles/settings-tools/_s.datatable.scss
Implement the subtext style in cells
=> feat(component/datatable): implement the subtext style in cells

.github/workflows/push.yml, .github/workflows/release.yml, package.json, packages/gatsby-theme-styleguide/package.json, packages/gatsby-theme-styleguide/src/components/IconViewer/IconTile.js, packages/gatsby-theme-styleguide/src/components/IconViewer/IconViewer.js, yarn.lock
=> feat(icons): use new ads-icons-react package

packages/styles/components/_c.stepper.scss, yarn.lock
Compact variation - displaying progress on first step
GitHub issue number or Jira issue URL
Related issue: https://github.com/adeo/mozaic-vue/issues/1931
=> fix(components/stepper): compact variation - displaying progress on first step

README.md
=> docs(readme): update dead link

packages/styles/components/_c.datatable-tools.scss, packages/styles/components/_c.menu.scss, packages/styles/components/_c.password-input.scss, packages/styles/components/_c.segmented-control.scss, packages/styles/components/_c.stepper.scss, packages/styles/components/_c.tag.scss
Update of focus states
GitHub issue number or Jira issue URL:
Resolves #1592
=> feat(components/a11y): update of focus states

commitlint.config.mjs, package.json, yarn.lock
Upgrade **commitlint** to last major version **v19+**
=> chore(deps/commitlin): upgrade commitlint to latest major version v19+

.github/workflows/push.yml, .github/workflows/release.yml, .husky/commit-msg, .husky/pre-commit, package.json, yarn.lock
Upgrade **husky** to its latest major version **v9+**
=> chore(deps/husky): upgrade husky to its latest major version v9+

packages/styles/components/_c.autocomplete.scss, packages/styles/components/_c.dropdown.scss, packages/styles/components/_c.listbox.scss, packages/styles/settings-tools/_s.autocomplete.scss, packages/styles/settings-tools/_s.dropdown.scss
=> feat(form): reduce to 6rem the min-width

packages/styles/components/_c.segmented-control.scss
=> feat(segment-control): enhance label management

packages/styles/components/_c.layer.scss
https://github.com/adeo/mozaic-vue/issues/2033
=> fix(layer): change max-height to height

packages/tokens/BricomanProperties/color/button.json, packages/tokens/BricomanProperties/color/flag.json
=> feat(tools/tokens): update Bricoman preset for Button and Flag

packages/tokens/BricomanProperties/color/button.json, packages/tokens/BricomanProperties/color/stepper.json
=> feat(bricoman/tokens): update button and stepper tokens

packages/styles/components/_c.layer.scss, packages/styles/settings-tools/_s.modal.scss, packages/styles/settings-tools/_s.overlay.scss
[GitHub issue number or Jira issue URL: 1637](https://github.com/adeo/mozaic-design-system/issues/1637)
=> feat(modal): add positions variables
